project_id = "rboiblptylnsgcciutrk"

[functions.setup-demo-users]
verify_jwt = false

[functions.predict-consumption]
verify_jwt = false

[functions.manage-jornadas]
verify_jwt = false

[functions.issue-document]
verify_jwt = true

[functions.send-jornada-summary]
verify_jwt = false

[functions.send-financial-summary]
verify_jwt = false

[functions.parse-invoice]
verify_jwt = true

[functions.create-worker-user]
verify_jwt = false

[functions.extract-invoice]
verify_jwt = false

[functions.check-feature-flag]
verify_jwt = false