-- ╔══════════════════════════════════════════════════════════════╗
-- ║  STOCKIA / DiStock — CONSTRAINTS                          ║
-- ║  Generated: 2026-02-23                                    ║
-- ╚══════════════════════════════════════════════════════════════╝

ALTER TABLE public.admin_audit_logs ADD CONSTRAINT admin_audit_logs_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES profiles(id);
ALTER TABLE public.admin_audit_logs ADD CONSTRAINT admin_audit_logs_target_worker_id_fkey FOREIGN KEY (target_worker_id) REFERENCES profiles(id);
ALTER TABLE public.admin_audit_logs ADD CONSTRAINT admin_audit_logs_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.admin_audit_logs ADD CONSTRAINT admin_audit_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.app_audit_events ADD CONSTRAINT app_audit_events_status_check CHECK ((status = ANY (ARRAY['success'::text, 'fail'::text])));
ALTER TABLE public.app_audit_events ADD CONSTRAINT app_audit_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.app_audit_events ADD CONSTRAINT app_audit_events_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE SET NULL;
ALTER TABLE public.app_audit_events ADD CONSTRAINT app_audit_events_pkey PRIMARY KEY (id);
ALTER TABLE public.app_error_logs ADD CONSTRAINT app_error_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.app_error_logs ADD CONSTRAINT app_error_logs_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE SET NULL;
ALTER TABLE public.app_error_logs ADD CONSTRAINT app_error_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.cash_registers ADD CONSTRAINT cash_registers_jornada_id_fkey FOREIGN KEY (jornada_id) REFERENCES jornadas(id) ON DELETE CASCADE;
ALTER TABLE public.cash_registers ADD CONSTRAINT cash_registers_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.cash_registers ADD CONSTRAINT cash_registers_pkey PRIMARY KEY (id);
ALTER TABLE public.cash_registers ADD CONSTRAINT cash_registers_jornada_id_key UNIQUE (jornada_id);
ALTER TABLE public.cocktail_addons ADD CONSTRAINT cocktail_addons_addon_id_fkey FOREIGN KEY (addon_id) REFERENCES product_addons(id) ON DELETE CASCADE;
ALTER TABLE public.cocktail_addons ADD CONSTRAINT cocktail_addons_cocktail_id_fkey FOREIGN KEY (cocktail_id) REFERENCES cocktails(id) ON DELETE CASCADE;
ALTER TABLE public.cocktail_addons ADD CONSTRAINT cocktail_addons_pkey PRIMARY KEY (cocktail_id, addon_id);
ALTER TABLE public.cocktail_ingredients ADD CONSTRAINT mixer_slot_consistency CHECK ((((is_mixer_slot = false) AND (mixer_category IS NULL)) OR ((is_mixer_slot = true) AND (product_id IS NULL))));
ALTER TABLE public.cocktail_ingredients ADD CONSTRAINT valid_mixer_category CHECK (((mixer_category IS NULL) OR (mixer_category = ANY (ARRAY['latas'::text, 'redbull'::text]))));
ALTER TABLE public.cocktail_ingredients ADD CONSTRAINT cocktail_ingredients_cocktail_id_fkey FOREIGN KEY (cocktail_id) REFERENCES cocktails(id) ON DELETE CASCADE;
ALTER TABLE public.cocktail_ingredients ADD CONSTRAINT cocktail_ingredients_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.cocktail_ingredients ADD CONSTRAINT cocktail_ingredients_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.cocktail_ingredients ADD CONSTRAINT cocktail_ingredients_pkey PRIMARY KEY (id);
ALTER TABLE public.cocktails ADD CONSTRAINT cocktails_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.cocktails ADD CONSTRAINT cocktails_pkey PRIMARY KEY (id);
ALTER TABLE public.courtesy_qr ADD CONSTRAINT courtesy_qr_status_check CHECK ((status = ANY (ARRAY['active'::text, 'redeemed'::text, 'expired'::text, 'cancelled'::text])));
ALTER TABLE public.courtesy_qr ADD CONSTRAINT courtesy_qr_product_id_fkey FOREIGN KEY (product_id) REFERENCES cocktails(id);
ALTER TABLE public.courtesy_qr ADD CONSTRAINT courtesy_qr_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.courtesy_qr ADD CONSTRAINT courtesy_qr_pkey PRIMARY KEY (id);
ALTER TABLE public.courtesy_qr ADD CONSTRAINT courtesy_qr_code_key UNIQUE (code);
ALTER TABLE public.courtesy_redemptions ADD CONSTRAINT courtesy_redemptions_result_check CHECK ((result = ANY (ARRAY['success'::text, 'fail'::text])));
ALTER TABLE public.courtesy_redemptions ADD CONSTRAINT courtesy_redemptions_courtesy_id_fkey FOREIGN KEY (courtesy_id) REFERENCES courtesy_qr(id);
ALTER TABLE public.courtesy_redemptions ADD CONSTRAINT courtesy_redemptions_jornada_id_fkey FOREIGN KEY (jornada_id) REFERENCES jornadas(id);
ALTER TABLE public.courtesy_redemptions ADD CONSTRAINT courtesy_redemptions_pos_id_fkey FOREIGN KEY (pos_id) REFERENCES pos_terminals(id);
ALTER TABLE public.courtesy_redemptions ADD CONSTRAINT courtesy_redemptions_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES sales(id);
ALTER TABLE public.courtesy_redemptions ADD CONSTRAINT courtesy_redemptions_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.courtesy_redemptions ADD CONSTRAINT courtesy_redemptions_pkey PRIMARY KEY (id);
ALTER TABLE public.demo_event_logs ADD CONSTRAINT demo_event_logs_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.demo_event_logs ADD CONSTRAINT demo_event_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.developer_feature_flags ADD CONSTRAINT developer_feature_flags_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id);
ALTER TABLE public.developer_feature_flags ADD CONSTRAINT developer_feature_flags_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.developer_feature_flags ADD CONSTRAINT developer_feature_flags_pkey PRIMARY KEY (id);
ALTER TABLE public.developer_feature_flags ADD CONSTRAINT developer_feature_flags_venue_id_key_key UNIQUE (venue_id, key);
ALTER TABLE public.developer_flag_audit ADD CONSTRAINT developer_flag_audit_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id);
ALTER TABLE public.developer_flag_audit ADD CONSTRAINT developer_flag_audit_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.developer_flag_audit ADD CONSTRAINT developer_flag_audit_pkey PRIMARY KEY (id);
ALTER TABLE public.developer_reset_audit ADD CONSTRAINT developer_reset_audit_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.developer_reset_audit ADD CONSTRAINT developer_reset_audit_pkey PRIMARY KEY (id);
ALTER TABLE public.expense_lines ADD CONSTRAINT expense_lines_purchase_id_fkey FOREIGN KEY (purchase_id) REFERENCES purchases(id) ON DELETE CASCADE;
ALTER TABLE public.expense_lines ADD CONSTRAINT expense_lines_pkey PRIMARY KEY (id);
ALTER TABLE public.expenses ADD CONSTRAINT expenses_expense_type_check CHECK ((expense_type = ANY (ARRAY['operacional'::text, 'no_operacional'::text])));
ALTER TABLE public.expenses ADD CONSTRAINT expenses_payment_method_check CHECK ((payment_method = ANY (ARRAY['cash'::text, 'card'::text])));
ALTER TABLE public.expenses ADD CONSTRAINT expenses_jornada_id_fkey FOREIGN KEY (jornada_id) REFERENCES jornadas(id);
ALTER TABLE public.expenses ADD CONSTRAINT expenses_pos_id_fkey FOREIGN KEY (pos_id) REFERENCES pos_terminals(id);
ALTER TABLE public.expenses ADD CONSTRAINT expenses_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.expenses ADD CONSTRAINT expenses_pkey PRIMARY KEY (id);
ALTER TABLE public.feature_flags ADD CONSTRAINT feature_flags_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.feature_flags ADD CONSTRAINT feature_flags_pkey PRIMARY KEY (id);
ALTER TABLE public.feature_flags ADD CONSTRAINT feature_flags_venue_id_feature_key_key UNIQUE (venue_id, feature_key);
ALTER TABLE public.feature_flags_master ADD CONSTRAINT feature_flags_master_pkey PRIMARY KEY (key);
ALTER TABLE public.gross_income_entries ADD CONSTRAINT gross_income_entries_source_type_check CHECK ((source_type = ANY (ARRAY['sale'::text, 'ticket'::text, 'manual'::text])));
ALTER TABLE public.gross_income_entries ADD CONSTRAINT gross_income_entries_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE public.gross_income_entries ADD CONSTRAINT gross_income_entries_jornada_id_fkey FOREIGN KEY (jornada_id) REFERENCES jornadas(id);
ALTER TABLE public.gross_income_entries ADD CONSTRAINT gross_income_entries_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.gross_income_entries ADD CONSTRAINT gross_income_entries_pkey PRIMARY KEY (id);
ALTER TABLE public.invoicing_config ADD CONSTRAINT invoicing_config_receipt_mode_check CHECK ((receipt_mode = ANY (ARRAY['hybrid'::text, 'unified'::text])));
ALTER TABLE public.invoicing_config ADD CONSTRAINT invoicing_config_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.invoicing_config ADD CONSTRAINT invoicing_config_pkey PRIMARY KEY (id);
ALTER TABLE public.jornada_audit_log ADD CONSTRAINT jornada_audit_log_action_check CHECK ((action = ANY (ARRAY['opened'::text, 'closed'::text, 'auto_closed'::text, 'closed_by_new_open'::text, 'forced_close'::text, 'created_pending'::text])));
ALTER TABLE public.jornada_audit_log ADD CONSTRAINT jornada_audit_log_jornada_id_fkey FOREIGN KEY (jornada_id) REFERENCES jornadas(id) ON DELETE CASCADE;
ALTER TABLE public.jornada_audit_log ADD CONSTRAINT jornada_audit_log_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.jornada_audit_log ADD CONSTRAINT jornada_audit_log_pkey PRIMARY KEY (id);
ALTER TABLE public.jornada_cash_closings ADD CONSTRAINT jornada_cash_closings_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.jornada_cash_closings ADD CONSTRAINT jornada_cash_closings_jornada_id_fkey FOREIGN KEY (jornada_id) REFERENCES jornadas(id) ON DELETE CASCADE;
ALTER TABLE public.jornada_cash_closings ADD CONSTRAINT jornada_cash_closings_pos_id_fkey FOREIGN KEY (pos_id) REFERENCES pos_terminals(id);
ALTER TABLE public.jornada_cash_closings ADD CONSTRAINT jornada_cash_closings_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.jornada_cash_closings ADD CONSTRAINT jornada_cash_closings_pkey PRIMARY KEY (id);
ALTER TABLE public.jornada_cash_openings ADD CONSTRAINT jornada_cash_openings_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.jornada_cash_openings ADD CONSTRAINT jornada_cash_openings_jornada_id_fkey FOREIGN KEY (jornada_id) REFERENCES jornadas(id) ON DELETE CASCADE;
ALTER TABLE public.jornada_cash_openings ADD CONSTRAINT jornada_cash_openings_pos_id_fkey FOREIGN KEY (pos_id) REFERENCES pos_terminals(id) ON DELETE CASCADE;
ALTER TABLE public.jornada_cash_openings ADD CONSTRAINT jornada_cash_openings_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.jornada_cash_openings ADD CONSTRAINT jornada_cash_openings_pkey PRIMARY KEY (id);
ALTER TABLE public.jornada_cash_openings ADD CONSTRAINT jornada_cash_openings_jornada_id_pos_id_key UNIQUE (jornada_id, pos_id);
ALTER TABLE public.jornada_cash_pos_defaults ADD CONSTRAINT jornada_cash_pos_defaults_pos_id_fkey FOREIGN KEY (pos_id) REFERENCES pos_terminals(id) ON DELETE CASCADE;
ALTER TABLE public.jornada_cash_pos_defaults ADD CONSTRAINT jornada_cash_pos_defaults_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.jornada_cash_pos_defaults ADD CONSTRAINT jornada_cash_pos_defaults_pkey PRIMARY KEY (id);
ALTER TABLE public.jornada_cash_pos_defaults ADD CONSTRAINT jornada_cash_pos_defaults_venue_id_pos_id_key UNIQUE (venue_id, pos_id);
ALTER TABLE public.jornada_cash_settings ADD CONSTRAINT jornada_cash_settings_cash_opening_mode_check CHECK ((cash_opening_mode = ANY (ARRAY['prompt'::text, 'auto'::text])));
ALTER TABLE public.jornada_cash_settings ADD CONSTRAINT jornada_cash_settings_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.jornada_cash_settings ADD CONSTRAINT jornada_cash_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.jornada_cash_settings ADD CONSTRAINT jornada_cash_settings_venue_id_key UNIQUE (venue_id);
ALTER TABLE public.jornada_config ADD CONSTRAINT jornada_config_dia_semana_check CHECK (((dia_semana >= 0) AND (dia_semana <= 6)));
ALTER TABLE public.jornada_config ADD CONSTRAINT jornada_config_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.jornada_config ADD CONSTRAINT jornada_config_pkey PRIMARY KEY (id);
ALTER TABLE public.jornada_config ADD CONSTRAINT jornada_config_dia_semana_key UNIQUE (dia_semana);
ALTER TABLE public.jornada_financial_summary ADD CONSTRAINT jornada_financial_summary_closed_by_fkey FOREIGN KEY (closed_by) REFERENCES profiles(id);
ALTER TABLE public.jornada_financial_summary ADD CONSTRAINT jornada_financial_summary_jornada_id_fkey FOREIGN KEY (jornada_id) REFERENCES jornadas(id);
ALTER TABLE public.jornada_financial_summary ADD CONSTRAINT jornada_financial_summary_pos_id_fkey FOREIGN KEY (pos_id) REFERENCES pos_terminals(id);
ALTER TABLE public.jornada_financial_summary ADD CONSTRAINT jornada_financial_summary_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.jornada_financial_summary ADD CONSTRAINT jornada_financial_summary_pkey PRIMARY KEY (id);
ALTER TABLE public.jornada_financial_summary ADD CONSTRAINT unique_jornada_pos_type_summary UNIQUE (jornada_id, pos_id, pos_type);
ALTER TABLE public.jornadas ADD CONSTRAINT jornadas_estado_check CHECK ((estado = ANY (ARRAY['pendiente'::text, 'activa'::text, 'cerrada'::text])));
ALTER TABLE public.jornadas ADD CONSTRAINT jornadas_numero_jornada_check CHECK ((numero_jornada >= 1));
ALTER TABLE public.jornadas ADD CONSTRAINT jornadas_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.jornadas ADD CONSTRAINT jornadas_pkey PRIMARY KEY (id);
ALTER TABLE public.jornadas ADD CONSTRAINT jornadas_venue_numero_unique UNIQUE (venue_id, numero_jornada);
ALTER TABLE public.learning_product_mappings ADD CONSTRAINT learning_product_mappings_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE public.learning_product_mappings ADD CONSTRAINT learning_product_mappings_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.learning_product_mappings ADD CONSTRAINT learning_product_mappings_pkey PRIMARY KEY (id);
ALTER TABLE public.login_attempts ADD CONSTRAINT login_attempts_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.login_attempts ADD CONSTRAINT login_attempts_pkey PRIMARY KEY (id);
ALTER TABLE public.login_history ADD CONSTRAINT login_history_jornada_id_fkey FOREIGN KEY (jornada_id) REFERENCES jornadas(id);
ALTER TABLE public.login_history ADD CONSTRAINT login_history_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.login_history ADD CONSTRAINT login_history_pkey PRIMARY KEY (id);
ALTER TABLE public.notification_logs ADD CONSTRAINT notification_logs_jornada_id_fkey FOREIGN KEY (jornada_id) REFERENCES jornadas(id) ON DELETE SET NULL;
ALTER TABLE public.notification_logs ADD CONSTRAINT notification_logs_recipient_worker_id_fkey FOREIGN KEY (recipient_worker_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.notification_logs ADD CONSTRAINT notification_logs_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE SET NULL;
ALTER TABLE public.notification_logs ADD CONSTRAINT notification_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.notification_logs ADD CONSTRAINT notification_logs_idempotency_key_key UNIQUE (idempotency_key);
ALTER TABLE public.notification_preferences ADD CONSTRAINT notification_preferences_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.notification_preferences ADD CONSTRAINT notification_preferences_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.notification_preferences ADD CONSTRAINT notification_preferences_pkey PRIMARY KEY (id);
ALTER TABLE public.notification_preferences ADD CONSTRAINT notification_preferences_worker_id_event_type_channel_key UNIQUE (worker_id, event_type, channel);
ALTER TABLE public.open_bottle_events ADD CONSTRAINT open_bottle_events_event_type_check CHECK ((event_type = ANY (ARRAY['OPENED'::text, 'REDEEM_DEDUCT'::text, 'MANUAL_ADJUST'::text, 'COUNT'::text, 'CLOSE_BOTTLE'::text])));
ALTER TABLE public.open_bottle_events ADD CONSTRAINT open_bottle_events_open_bottle_id_fkey FOREIGN KEY (open_bottle_id) REFERENCES open_bottles(id) ON DELETE CASCADE;
ALTER TABLE public.open_bottle_events ADD CONSTRAINT open_bottle_events_pkey PRIMARY KEY (id);
ALTER TABLE public.open_bottles ADD CONSTRAINT open_bottles_remaining_ml_non_negative CHECK ((remaining_ml >= (0)::numeric));
ALTER TABLE public.open_bottles ADD CONSTRAINT open_bottles_status_check CHECK ((status = ANY (ARRAY['OPEN'::text, 'CLOSED'::text])));
ALTER TABLE public.open_bottles ADD CONSTRAINT open_bottles_location_id_fkey FOREIGN KEY (location_id) REFERENCES stock_locations(id) ON DELETE CASCADE;
ALTER TABLE public.open_bottles ADD CONSTRAINT open_bottles_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.open_bottles ADD CONSTRAINT open_bottles_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.open_bottles ADD CONSTRAINT open_bottles_pkey PRIMARY KEY (id);
ALTER TABLE public.operational_expenses ADD CONSTRAINT operational_expenses_amount_check CHECK ((amount >= (0)::numeric));
ALTER TABLE public.operational_expenses ADD CONSTRAINT operational_expenses_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.operational_expenses ADD CONSTRAINT operational_expenses_pkey PRIMARY KEY (id);
ALTER TABLE public.pickup_redemptions_log ADD CONSTRAINT pickup_redemptions_log_pickup_token_id_fkey FOREIGN KEY (pickup_token_id) REFERENCES pickup_tokens(id) ON DELETE SET NULL;
ALTER TABLE public.pickup_redemptions_log ADD CONSTRAINT pickup_redemptions_log_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE SET NULL;
ALTER TABLE public.pickup_redemptions_log ADD CONSTRAINT pickup_redemptions_log_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.pickup_redemptions_log ADD CONSTRAINT pickup_redemptions_log_pkey PRIMARY KEY (id);
ALTER TABLE public.pickup_tokens ADD CONSTRAINT pickup_tokens_source_check CHECK (((sale_id IS NOT NULL) OR (ticket_sale_id IS NOT NULL)));
ALTER TABLE public.pickup_tokens ADD CONSTRAINT pickup_tokens_bar_location_id_fkey FOREIGN KEY (bar_location_id) REFERENCES stock_locations(id);
ALTER TABLE public.pickup_tokens ADD CONSTRAINT pickup_tokens_cover_cocktail_id_fkey FOREIGN KEY (cover_cocktail_id) REFERENCES cocktails(id) ON DELETE SET NULL;
ALTER TABLE public.pickup_tokens ADD CONSTRAINT pickup_tokens_jornada_id_fkey FOREIGN KEY (jornada_id) REFERENCES jornadas(id);
ALTER TABLE public.pickup_tokens ADD CONSTRAINT pickup_tokens_redeemed_by_fkey FOREIGN KEY (redeemed_by) REFERENCES auth.users(id);
ALTER TABLE public.pickup_tokens ADD CONSTRAINT pickup_tokens_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE;
ALTER TABLE public.pickup_tokens ADD CONSTRAINT pickup_tokens_ticket_sale_id_fkey FOREIGN KEY (ticket_sale_id) REFERENCES ticket_sales(id) ON DELETE SET NULL;
ALTER TABLE public.pickup_tokens ADD CONSTRAINT pickup_tokens_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.pickup_tokens ADD CONSTRAINT pickup_tokens_pkey PRIMARY KEY (id);
ALTER TABLE public.pickup_tokens ADD CONSTRAINT pickup_tokens_token_key UNIQUE (token);
ALTER TABLE public.pos_terminals ADD CONSTRAINT pos_terminals_business_type_check CHECK ((business_type = ANY (ARRAY['tickets'::text, 'alcohol'::text, 'cloakroom'::text])));
ALTER TABLE public.pos_terminals ADD CONSTRAINT pos_terminals_pos_kind_check CHECK ((pos_kind = ANY (ARRAY['cashier'::text, 'scanner'::text])));
ALTER TABLE public.pos_terminals ADD CONSTRAINT pos_terminals_pos_type_check CHECK ((pos_type = ANY (ARRAY['alcohol_sales'::text, 'ticket_sales'::text, 'bar_redemption'::text])));
ALTER TABLE public.pos_terminals ADD CONSTRAINT pos_terminals_bar_location_id_fkey FOREIGN KEY (bar_location_id) REFERENCES stock_locations(id);
ALTER TABLE public.pos_terminals ADD CONSTRAINT pos_terminals_location_id_fkey FOREIGN KEY (location_id) REFERENCES stock_locations(id) ON DELETE RESTRICT;
ALTER TABLE public.pos_terminals ADD CONSTRAINT pos_terminals_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.pos_terminals ADD CONSTRAINT pos_terminals_pkey PRIMARY KEY (id);
ALTER TABLE public.product_addons ADD CONSTRAINT product_addons_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.product_addons ADD CONSTRAINT product_addons_pkey PRIMARY KEY (id);
ALTER TABLE public.product_name_mappings ADD CONSTRAINT product_name_mappings_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.product_name_mappings ADD CONSTRAINT product_name_mappings_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.product_name_mappings ADD CONSTRAINT product_name_mappings_pkey PRIMARY KEY (id);
ALTER TABLE public.product_name_mappings ADD CONSTRAINT product_name_mappings_raw_name_venue_id_key UNIQUE (raw_name, venue_id);
ALTER TABLE public.products ADD CONSTRAINT products_cost_per_unit_check CHECK ((cost_per_unit >= (0)::numeric));
ALTER TABLE public.products ADD CONSTRAINT products_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.products ADD CONSTRAINT products_pkey PRIMARY KEY (id);
ALTER TABLE public.products ADD CONSTRAINT products_code_key UNIQUE (code);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.provider_product_mappings ADD CONSTRAINT provider_product_mappings_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.provider_product_mappings ADD CONSTRAINT provider_product_mappings_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.provider_product_mappings ADD CONSTRAINT provider_product_mappings_pkey PRIMARY KEY (id);
ALTER TABLE public.provider_product_mappings ADD CONSTRAINT provider_product_mappings_venue_id_provider_name_raw_produc_key UNIQUE (venue_id, provider_name, raw_product_name);
ALTER TABLE public.purchase_documents ADD CONSTRAINT purchase_documents_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'ready'::text, 'confirmed'::text, 'error'::text])));
ALTER TABLE public.purchase_documents ADD CONSTRAINT purchase_documents_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES profiles(id);
ALTER TABLE public.purchase_documents ADD CONSTRAINT purchase_documents_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.purchase_documents ADD CONSTRAINT purchase_documents_pkey PRIMARY KEY (id);
ALTER TABLE public.purchase_import_audit ADD CONSTRAINT purchase_import_audit_purchase_document_id_fkey FOREIGN KEY (purchase_document_id) REFERENCES purchase_documents(id) ON DELETE CASCADE;
ALTER TABLE public.purchase_import_audit ADD CONSTRAINT purchase_import_audit_pkey PRIMARY KEY (id);
ALTER TABLE public.purchase_import_drafts ADD CONSTRAINT purchase_import_drafts_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'confirmed'::text, 'abandoned'::text])));
ALTER TABLE public.purchase_import_drafts ADD CONSTRAINT purchase_import_drafts_purchase_document_id_fkey FOREIGN KEY (purchase_document_id) REFERENCES purchase_documents(id) ON DELETE SET NULL;
ALTER TABLE public.purchase_import_drafts ADD CONSTRAINT purchase_import_drafts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.purchase_import_drafts ADD CONSTRAINT purchase_import_drafts_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.purchase_import_drafts ADD CONSTRAINT purchase_import_drafts_pkey PRIMARY KEY (id);
ALTER TABLE public.purchase_import_lines ADD CONSTRAINT purchase_import_lines_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE public.purchase_import_lines ADD CONSTRAINT purchase_import_lines_purchase_import_id_fkey FOREIGN KEY (purchase_import_id) REFERENCES purchase_imports(id) ON DELETE CASCADE;
ALTER TABLE public.purchase_import_lines ADD CONSTRAINT purchase_import_lines_pkey PRIMARY KEY (id);
ALTER TABLE public.purchase_import_taxes ADD CONSTRAINT purchase_import_taxes_purchase_import_id_fkey FOREIGN KEY (purchase_import_id) REFERENCES purchase_imports(id) ON DELETE CASCADE;
ALTER TABLE public.purchase_import_taxes ADD CONSTRAINT purchase_import_taxes_pkey PRIMARY KEY (id);
ALTER TABLE public.purchase_imports ADD CONSTRAINT purchase_imports_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.purchase_imports ADD CONSTRAINT purchase_imports_location_id_fkey FOREIGN KEY (location_id) REFERENCES stock_locations(id);
ALTER TABLE public.purchase_imports ADD CONSTRAINT purchase_imports_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.purchase_imports ADD CONSTRAINT purchase_imports_pkey PRIMARY KEY (id);
ALTER TABLE public.purchase_items ADD CONSTRAINT purchase_items_matched_product_id_fkey FOREIGN KEY (matched_product_id) REFERENCES products(id);
ALTER TABLE public.purchase_items ADD CONSTRAINT purchase_items_purchase_document_id_fkey FOREIGN KEY (purchase_document_id) REFERENCES purchase_documents(id) ON DELETE CASCADE;
ALTER TABLE public.purchase_items ADD CONSTRAINT purchase_items_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.purchase_items ADD CONSTRAINT purchase_items_pkey PRIMARY KEY (id);
ALTER TABLE public.purchase_lines ADD CONSTRAINT purchase_lines_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE public.purchase_lines ADD CONSTRAINT purchase_lines_purchase_id_fkey FOREIGN KEY (purchase_id) REFERENCES purchases(id) ON DELETE CASCADE;
ALTER TABLE public.purchase_lines ADD CONSTRAINT purchase_lines_pkey PRIMARY KEY (id);
ALTER TABLE public.purchases ADD CONSTRAINT purchases_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES auth.users(id);
ALTER TABLE public.purchases ADD CONSTRAINT purchases_location_id_fkey FOREIGN KEY (location_id) REFERENCES stock_locations(id);
ALTER TABLE public.purchases ADD CONSTRAINT purchases_purchase_import_id_fkey FOREIGN KEY (purchase_import_id) REFERENCES purchase_imports(id);
ALTER TABLE public.purchases ADD CONSTRAINT purchases_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.purchases ADD CONSTRAINT purchases_pkey PRIMARY KEY (id);
ALTER TABLE public.purchases ADD CONSTRAINT purchases_purchase_import_id_key UNIQUE (purchase_import_id);
ALTER TABLE public.replenishment_plan_items ADD CONSTRAINT replenishment_plan_items_quantity_check CHECK ((quantity > (0)::numeric));
ALTER TABLE public.replenishment_plan_items ADD CONSTRAINT replenishment_plan_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE public.replenishment_plan_items ADD CONSTRAINT replenishment_plan_items_replenishment_plan_id_fkey FOREIGN KEY (replenishment_plan_id) REFERENCES replenishment_plans(id) ON DELETE CASCADE;
ALTER TABLE public.replenishment_plan_items ADD CONSTRAINT replenishment_plan_items_to_location_id_fkey FOREIGN KEY (to_location_id) REFERENCES stock_locations(id);
ALTER TABLE public.replenishment_plan_items ADD CONSTRAINT replenishment_plan_items_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.replenishment_plan_items ADD CONSTRAINT replenishment_plan_items_pkey PRIMARY KEY (id);
ALTER TABLE public.replenishment_plans ADD CONSTRAINT replenishment_plans_jornada_id_fkey FOREIGN KEY (jornada_id) REFERENCES jornadas(id) ON DELETE SET NULL;
ALTER TABLE public.replenishment_plans ADD CONSTRAINT replenishment_plans_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.replenishment_plans ADD CONSTRAINT replenishment_plans_pkey PRIMARY KEY (id);
ALTER TABLE public.resettable_tables ADD CONSTRAINT resettable_tables_pkey PRIMARY KEY (key);
ALTER TABLE public.sale_item_addons ADD CONSTRAINT sale_item_addons_addon_id_fkey FOREIGN KEY (addon_id) REFERENCES product_addons(id) ON DELETE SET NULL;
ALTER TABLE public.sale_item_addons ADD CONSTRAINT sale_item_addons_sale_item_id_fkey FOREIGN KEY (sale_item_id) REFERENCES sale_items(id) ON DELETE CASCADE;
ALTER TABLE public.sale_item_addons ADD CONSTRAINT sale_item_addons_pkey PRIMARY KEY (id);
ALTER TABLE public.sale_items ADD CONSTRAINT sale_items_cocktail_id_fkey FOREIGN KEY (cocktail_id) REFERENCES cocktails(id);
ALTER TABLE public.sale_items ADD CONSTRAINT sale_items_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE;
ALTER TABLE public.sale_items ADD CONSTRAINT sale_items_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.sale_items ADD CONSTRAINT sale_items_pkey PRIMARY KEY (id);
ALTER TABLE public.sales ADD CONSTRAINT sales_sale_category_check CHECK ((sale_category = ANY (ARRAY['alcohol'::text, 'ticket'::text])));
ALTER TABLE public.sales ADD CONSTRAINT sales_bar_location_id_fkey FOREIGN KEY (bar_location_id) REFERENCES stock_locations(id);
ALTER TABLE public.sales ADD CONSTRAINT sales_jornada_id_fkey FOREIGN KEY (jornada_id) REFERENCES jornadas(id);
ALTER TABLE public.sales ADD CONSTRAINT sales_pos_id_fkey FOREIGN KEY (pos_id) REFERENCES pos_terminals(id);
ALTER TABLE public.sales ADD CONSTRAINT sales_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES auth.users(id);
ALTER TABLE public.sales ADD CONSTRAINT sales_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.sales ADD CONSTRAINT sales_pkey PRIMARY KEY (id);
ALTER TABLE public.sales_documents ADD CONSTRAINT sales_documents_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE;
ALTER TABLE public.sales_documents ADD CONSTRAINT sales_documents_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.sales_documents ADD CONSTRAINT sales_documents_pkey PRIMARY KEY (id);
ALTER TABLE public.sales_documents ADD CONSTRAINT sales_documents_sale_id_key UNIQUE (sale_id);
ALTER TABLE public.sidebar_config ADD CONSTRAINT sidebar_config_role_check CHECK ((role = ANY (ARRAY['admin'::text, 'gerencia'::text, 'vendedor'::text, 'bar'::text, 'ticket_seller'::text])));
ALTER TABLE public.sidebar_config ADD CONSTRAINT sidebar_config_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.sidebar_config ADD CONSTRAINT sidebar_config_pkey PRIMARY KEY (id);
ALTER TABLE public.sidebar_config ADD CONSTRAINT sidebar_config_venue_id_role_menu_key_key UNIQUE (venue_id, role, menu_key);
ALTER TABLE public.specific_tax_categories ADD CONSTRAINT specific_tax_categories_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.specific_tax_categories ADD CONSTRAINT specific_tax_categories_pkey PRIMARY KEY (id);
ALTER TABLE public.specific_tax_categories ADD CONSTRAINT specific_tax_categories_code_key UNIQUE (code);
ALTER TABLE public.stock_alerts ADD CONSTRAINT stock_alerts_jornada_id_fkey FOREIGN KEY (jornada_id) REFERENCES jornadas(id);
ALTER TABLE public.stock_alerts ADD CONSTRAINT stock_alerts_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.stock_alerts ADD CONSTRAINT stock_alerts_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.stock_alerts ADD CONSTRAINT stock_alerts_pkey PRIMARY KEY (id);
ALTER TABLE public.stock_balances ADD CONSTRAINT stock_balances_location_id_fkey FOREIGN KEY (location_id) REFERENCES stock_locations(id) ON DELETE CASCADE;
ALTER TABLE public.stock_balances ADD CONSTRAINT stock_balances_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.stock_balances ADD CONSTRAINT stock_balances_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.stock_balances ADD CONSTRAINT stock_balances_pkey PRIMARY KEY (id);
ALTER TABLE public.stock_balances ADD CONSTRAINT stock_balances_product_id_location_id_key UNIQUE (product_id, location_id);
ALTER TABLE public.stock_intake_batches ADD CONSTRAINT stock_intake_batches_default_location_id_fkey FOREIGN KEY (default_location_id) REFERENCES stock_locations(id);
ALTER TABLE public.stock_intake_batches ADD CONSTRAINT stock_intake_batches_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.stock_intake_batches ADD CONSTRAINT stock_intake_batches_pkey PRIMARY KEY (id);
ALTER TABLE public.stock_intake_items ADD CONSTRAINT stock_intake_items_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES stock_intake_batches(id) ON DELETE CASCADE;
ALTER TABLE public.stock_intake_items ADD CONSTRAINT stock_intake_items_location_id_fkey FOREIGN KEY (location_id) REFERENCES stock_locations(id);
ALTER TABLE public.stock_intake_items ADD CONSTRAINT stock_intake_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE public.stock_intake_items ADD CONSTRAINT stock_intake_items_tax_category_id_fkey FOREIGN KEY (tax_category_id) REFERENCES specific_tax_categories(id);
ALTER TABLE public.stock_intake_items ADD CONSTRAINT stock_intake_items_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.stock_intake_items ADD CONSTRAINT stock_intake_items_pkey PRIMARY KEY (id);
ALTER TABLE public.stock_location_minimums ADD CONSTRAINT stock_location_minimums_location_id_fkey FOREIGN KEY (location_id) REFERENCES stock_locations(id) ON DELETE CASCADE;
ALTER TABLE public.stock_location_minimums ADD CONSTRAINT stock_location_minimums_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.stock_location_minimums ADD CONSTRAINT stock_location_minimums_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.stock_location_minimums ADD CONSTRAINT stock_location_minimums_pkey PRIMARY KEY (id);
ALTER TABLE public.stock_location_minimums ADD CONSTRAINT stock_location_minimums_product_id_location_id_key UNIQUE (product_id, location_id);
ALTER TABLE public.stock_locations ADD CONSTRAINT stock_locations_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.stock_locations ADD CONSTRAINT stock_locations_pkey PRIMARY KEY (id);
ALTER TABLE public.stock_lots ADD CONSTRAINT positive_quantity CHECK ((quantity >= (0)::numeric));
ALTER TABLE public.stock_lots ADD CONSTRAINT valid_source CHECK ((source = ANY (ARRAY['manual'::text, 'excel'::text, 'transfer'::text, 'invoice'::text, 'demo'::text, 'legacy_migration'::text])));
ALTER TABLE public.stock_lots ADD CONSTRAINT stock_lots_location_id_fkey FOREIGN KEY (location_id) REFERENCES stock_locations(id) ON DELETE CASCADE;
ALTER TABLE public.stock_lots ADD CONSTRAINT stock_lots_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.stock_lots ADD CONSTRAINT stock_lots_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.stock_lots ADD CONSTRAINT stock_lots_pkey PRIMARY KEY (id);
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_percent_visual_check CHECK (((percent_visual IS NULL) OR ((percent_visual >= 0) AND (percent_visual <= 100))));
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_from_location_id_fkey FOREIGN KEY (from_location_id) REFERENCES stock_locations(id);
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_jornada_id_fkey FOREIGN KEY (jornada_id) REFERENCES jornadas(id);
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_pickup_token_id_fkey FOREIGN KEY (pickup_token_id) REFERENCES pickup_tokens(id) ON DELETE SET NULL;
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_stock_lot_id_fkey FOREIGN KEY (stock_lot_id) REFERENCES stock_lots(id);
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_to_location_id_fkey FOREIGN KEY (to_location_id) REFERENCES stock_locations(id);
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_transfer_id_fkey FOREIGN KEY (transfer_id) REFERENCES stock_transfers(id);
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_pkey PRIMARY KEY (id);
ALTER TABLE public.stock_predictions ADD CONSTRAINT stock_predictions_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.stock_predictions ADD CONSTRAINT stock_predictions_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.stock_predictions ADD CONSTRAINT stock_predictions_pkey PRIMARY KEY (id);
ALTER TABLE public.stock_transfer_items ADD CONSTRAINT stock_transfer_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE public.stock_transfer_items ADD CONSTRAINT stock_transfer_items_transfer_id_fkey FOREIGN KEY (transfer_id) REFERENCES stock_transfers(id) ON DELETE CASCADE;
ALTER TABLE public.stock_transfer_items ADD CONSTRAINT stock_transfer_items_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.stock_transfer_items ADD CONSTRAINT stock_transfer_items_pkey PRIMARY KEY (id);
ALTER TABLE public.stock_transfers ADD CONSTRAINT stock_transfers_from_location_id_fkey FOREIGN KEY (from_location_id) REFERENCES stock_locations(id);
ALTER TABLE public.stock_transfers ADD CONSTRAINT stock_transfers_jornada_id_fkey FOREIGN KEY (jornada_id) REFERENCES jornadas(id);
ALTER TABLE public.stock_transfers ADD CONSTRAINT stock_transfers_to_location_id_fkey FOREIGN KEY (to_location_id) REFERENCES stock_locations(id);
ALTER TABLE public.stock_transfers ADD CONSTRAINT stock_transfers_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.stock_transfers ADD CONSTRAINT stock_transfers_pkey PRIMARY KEY (id);
ALTER TABLE public.supplier_product_aliases ADD CONSTRAINT supplier_product_aliases_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.supplier_product_aliases ADD CONSTRAINT supplier_product_aliases_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.supplier_product_aliases ADD CONSTRAINT supplier_product_aliases_pkey PRIMARY KEY (id);
ALTER TABLE public.supplier_product_aliases ADD CONSTRAINT supplier_product_aliases_venue_id_supplier_name_normalized__key UNIQUE (venue_id, supplier_name, normalized_text);
ALTER TABLE public.ticket_sale_items ADD CONSTRAINT ticket_sale_items_ticket_sale_id_fkey FOREIGN KEY (ticket_sale_id) REFERENCES ticket_sales(id) ON DELETE CASCADE;
ALTER TABLE public.ticket_sale_items ADD CONSTRAINT ticket_sale_items_ticket_type_id_fkey FOREIGN KEY (ticket_type_id) REFERENCES ticket_types(id);
ALTER TABLE public.ticket_sale_items ADD CONSTRAINT ticket_sale_items_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.ticket_sale_items ADD CONSTRAINT ticket_sale_items_pkey PRIMARY KEY (id);
ALTER TABLE public.ticket_sales ADD CONSTRAINT ticket_sales_jornada_id_fkey FOREIGN KEY (jornada_id) REFERENCES jornadas(id);
ALTER TABLE public.ticket_sales ADD CONSTRAINT ticket_sales_pos_id_fkey FOREIGN KEY (pos_id) REFERENCES pos_terminals(id);
ALTER TABLE public.ticket_sales ADD CONSTRAINT ticket_sales_sold_by_worker_id_fkey FOREIGN KEY (sold_by_worker_id) REFERENCES profiles(id);
ALTER TABLE public.ticket_sales ADD CONSTRAINT ticket_sales_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.ticket_sales ADD CONSTRAINT ticket_sales_pkey PRIMARY KEY (id);
ALTER TABLE public.ticket_sales ADD CONSTRAINT ticket_sales_ticket_number_key UNIQUE (ticket_number);
ALTER TABLE public.ticket_types ADD CONSTRAINT ticket_types_cover_cocktail_id_fkey FOREIGN KEY (cover_cocktail_id) REFERENCES cocktails(id) ON DELETE SET NULL;
ALTER TABLE public.ticket_types ADD CONSTRAINT ticket_types_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.ticket_types ADD CONSTRAINT ticket_types_pkey PRIMARY KEY (id);
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_role_key UNIQUE (user_id, role);
ALTER TABLE public.user_venue_roles ADD CONSTRAINT user_venue_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.user_venue_roles ADD CONSTRAINT user_venue_roles_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.user_venue_roles ADD CONSTRAINT user_venue_roles_pkey PRIMARY KEY (id);
ALTER TABLE public.venue_feature_flags ADD CONSTRAINT venue_feature_flags_flag_key_fkey FOREIGN KEY (flag_key) REFERENCES feature_flags_master(key) ON DELETE CASCADE;
ALTER TABLE public.venue_feature_flags ADD CONSTRAINT venue_feature_flags_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE;
ALTER TABLE public.venue_feature_flags ADD CONSTRAINT venue_feature_flags_pkey PRIMARY KEY (venue_id, flag_key);
ALTER TABLE public.venues ADD CONSTRAINT venues_pkey PRIMARY KEY (id);
ALTER TABLE public.venues ADD CONSTRAINT venues_slug_key UNIQUE (slug);
ALTER TABLE public.waste_requests ADD CONSTRAINT waste_requests_bottle_type_check CHECK ((bottle_type = ANY (ARRAY['cerrada'::text, 'abierta'::text])));
ALTER TABLE public.waste_requests ADD CONSTRAINT waste_requests_percent_visual_check CHECK (((percent_visual IS NULL) OR ((percent_visual >= 0) AND (percent_visual <= 100))));
ALTER TABLE public.waste_requests ADD CONSTRAINT waste_requests_quantity_check CHECK ((quantity > (0)::numeric));
ALTER TABLE public.waste_requests ADD CONSTRAINT waste_requests_status_check CHECK ((status = ANY (ARRAY['PENDING_APPROVAL'::text, 'APPROVED'::text, 'REJECTED'::text])));
ALTER TABLE public.waste_requests ADD CONSTRAINT waste_requests_unit_type_check CHECK ((unit_type = ANY (ARRAY['ml'::text, 'unit'::text])));
ALTER TABLE public.waste_requests ADD CONSTRAINT waste_requests_jornada_id_fkey FOREIGN KEY (jornada_id) REFERENCES jornadas(id);
ALTER TABLE public.waste_requests ADD CONSTRAINT waste_requests_location_id_fkey FOREIGN KEY (location_id) REFERENCES stock_locations(id);
ALTER TABLE public.waste_requests ADD CONSTRAINT waste_requests_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE public.waste_requests ADD CONSTRAINT waste_requests_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.waste_requests ADD CONSTRAINT waste_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.worker_roles ADD CONSTRAINT worker_roles_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES venues(id);
ALTER TABLE public.worker_roles ADD CONSTRAINT worker_roles_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.worker_roles ADD CONSTRAINT worker_roles_pkey PRIMARY KEY (id);
ALTER TABLE public.worker_roles ADD CONSTRAINT worker_roles_unique UNIQUE (worker_id, role);
