-- ╔══════════════════════════════════════════════════════════════╗
-- ║  STOCKIA / DiStock — INDEXES                              ║
-- ║  Generated: 2026-02-23                                    ║
-- ╚══════════════════════════════════════════════════════════════╝

CREATE INDEX idx_admin_audit_logs_venue ON public.admin_audit_logs USING btree (venue_id);
CREATE INDEX idx_app_audit_events_action ON public.app_audit_events USING btree (action);
CREATE INDEX idx_app_audit_events_action_created_at ON public.app_audit_events USING btree (action, created_at DESC);
CREATE INDEX idx_app_audit_events_created_at ON public.app_audit_events USING btree (created_at DESC);
CREATE INDEX idx_app_audit_events_status ON public.app_audit_events USING btree (status);
CREATE INDEX idx_app_audit_events_status_created_at ON public.app_audit_events USING btree (status, created_at DESC);
CREATE INDEX idx_app_audit_events_venue_created_at ON public.app_audit_events USING btree (venue_id, created_at DESC);
CREATE INDEX idx_app_audit_events_venue_id ON public.app_audit_events USING btree (venue_id);
CREATE INDEX idx_app_error_logs_created_at ON public.app_error_logs USING btree (created_at DESC);
CREATE INDEX idx_app_error_logs_route_created_at ON public.app_error_logs USING btree (route, created_at DESC);
CREATE INDEX idx_app_error_logs_venue_created_at ON public.app_error_logs USING btree (venue_id, created_at DESC);
CREATE INDEX idx_app_error_logs_venue_id ON public.app_error_logs USING btree (venue_id);
CREATE UNIQUE INDEX cash_registers_jornada_id_key ON public.cash_registers USING btree (jornada_id);
CREATE INDEX idx_cash_registers_venue ON public.cash_registers USING btree (venue_id);
CREATE INDEX idx_cocktail_addons_addon ON public.cocktail_addons USING btree (addon_id);
CREATE INDEX idx_cocktail_addons_cocktail ON public.cocktail_addons USING btree (cocktail_id);
CREATE INDEX idx_cocktail_ingredients_venue_id ON public.cocktail_ingredients USING btree (venue_id);
CREATE INDEX idx_cocktails_venue_id ON public.cocktails USING btree (venue_id);
CREATE UNIQUE INDEX courtesy_qr_code_key ON public.courtesy_qr USING btree (code);
CREATE INDEX idx_courtesy_qr_code ON public.courtesy_qr USING btree (code);
CREATE INDEX idx_courtesy_qr_venue_status ON public.courtesy_qr USING btree (venue_id, status);
CREATE INDEX idx_courtesy_redemptions_courtesy ON public.courtesy_redemptions USING btree (courtesy_id);
CREATE INDEX idx_demo_event_logs_venue_event ON public.demo_event_logs USING btree (venue_id, event_type, created_at DESC);
CREATE UNIQUE INDEX developer_feature_flags_venue_id_key_key ON public.developer_feature_flags USING btree (venue_id, key);
CREATE INDEX idx_developer_reset_audit_developer ON public.developer_reset_audit USING btree (developer_user_id, executed_at DESC);
CREATE INDEX idx_developer_reset_audit_venue ON public.developer_reset_audit USING btree (venue_id, executed_at DESC);
CREATE INDEX idx_expenses_created_at ON public.expenses USING btree (created_at DESC);
CREATE INDEX idx_expenses_jornada ON public.expenses USING btree (jornada_id);
CREATE INDEX idx_expenses_jornada_created_at ON public.expenses USING btree (jornada_id, created_at DESC);
CREATE INDEX idx_expenses_source ON public.expenses USING btree (source_type, source_id);
CREATE INDEX idx_expenses_type ON public.expenses USING btree (expense_type);
CREATE INDEX idx_expenses_venue ON public.expenses USING btree (venue_id);
CREATE INDEX idx_expenses_venue_created_at ON public.expenses USING btree (venue_id, created_at DESC);
CREATE INDEX idx_expenses_venue_jornada ON public.expenses USING btree (venue_id, jornada_id);
CREATE UNIQUE INDEX feature_flags_venue_id_feature_key_key ON public.feature_flags USING btree (venue_id, feature_key);
CREATE INDEX idx_feature_flags_venue_key ON public.feature_flags USING btree (venue_id, feature_key);
CREATE INDEX idx_gross_income_entries_created_at ON public.gross_income_entries USING btree (created_at);
CREATE INDEX idx_gross_income_entries_jornada_id ON public.gross_income_entries USING btree (jornada_id);
CREATE INDEX idx_gross_income_entries_source ON public.gross_income_entries USING btree (source_type, source_id);
CREATE INDEX idx_gross_income_jornada_created_at ON public.gross_income_entries USING btree (jornada_id, created_at DESC);
CREATE INDEX idx_gross_income_venue_created_at ON public.gross_income_entries USING btree (venue_id, created_at DESC);
CREATE INDEX idx_gross_income_venue_jornada ON public.gross_income_entries USING btree (venue_id, jornada_id);
CREATE INDEX idx_invoicing_config_receipt_mode ON public.invoicing_config USING btree (receipt_mode);
CREATE INDEX idx_invoicing_config_venue ON public.invoicing_config USING btree (venue_id);
CREATE INDEX idx_jornada_audit_log_created ON public.jornada_audit_log USING btree (created_at DESC);
CREATE INDEX idx_jornada_audit_log_jornada ON public.jornada_audit_log USING btree (jornada_id);
CREATE INDEX idx_jornada_audit_log_venue ON public.jornada_audit_log USING btree (venue_id);
CREATE INDEX idx_jornada_cash_closings_jornada ON public.jornada_cash_closings USING btree (jornada_id);
CREATE UNIQUE INDEX idx_jornada_cash_closings_unique ON public.jornada_cash_closings USING btree (jornada_id, pos_id);
CREATE INDEX idx_jornada_cash_closings_venue ON public.jornada_cash_closings USING btree (venue_id);
CREATE UNIQUE INDEX jornada_cash_openings_jornada_id_pos_id_key ON public.jornada_cash_openings USING btree (jornada_id, pos_id);
CREATE UNIQUE INDEX jornada_cash_pos_defaults_venue_id_pos_id_key ON public.jornada_cash_pos_defaults USING btree (venue_id, pos_id);
CREATE UNIQUE INDEX jornada_cash_settings_venue_id_key ON public.jornada_cash_settings USING btree (venue_id);
CREATE INDEX idx_jornada_config_venue ON public.jornada_config USING btree (venue_id);
CREATE UNIQUE INDEX jornada_config_dia_semana_key ON public.jornada_config USING btree (dia_semana);
CREATE INDEX idx_jornada_financial_summary_pos_type ON public.jornada_financial_summary USING btree (jornada_id, pos_type);
CREATE UNIQUE INDEX unique_jornada_pos_type_summary ON public.jornada_financial_summary USING btree (jornada_id, pos_id, pos_type);
CREATE INDEX idx_jornadas_estado ON public.jornadas USING btree (estado);
CREATE INDEX idx_jornadas_fecha ON public.jornadas USING btree (fecha);
CREATE UNIQUE INDEX idx_jornadas_one_active_per_venue ON public.jornadas USING btree (venue_id) WHERE (estado = 'activa'::text);
CREATE INDEX idx_jornadas_requires_review ON public.jornadas USING btree (requires_review) WHERE (requires_review = true);
CREATE INDEX idx_jornadas_semana ON public.jornadas USING btree (semana_inicio, numero_jornada);
CREATE INDEX idx_jornadas_venue_created_at ON public.jornadas USING btree (venue_id, created_at DESC);
CREATE INDEX idx_jornadas_venue_estado ON public.jornadas USING btree (venue_id, estado);
CREATE UNIQUE INDEX jornadas_venue_numero_unique ON public.jornadas USING btree (venue_id, numero_jornada);
CREATE INDEX idx_learning_mappings_lookup ON public.learning_product_mappings USING btree (venue_id, supplier_rut, raw_text);
CREATE INDEX idx_login_history_jornada ON public.login_history USING btree (jornada_id);
CREATE INDEX idx_login_history_login_at ON public.login_history USING btree (login_at DESC);
CREATE INDEX idx_login_history_user_id ON public.login_history USING btree (user_id);
CREATE INDEX idx_login_history_venue ON public.login_history USING btree (venue_id);
CREATE INDEX idx_notification_logs_event_type ON public.notification_logs USING btree (event_type);
CREATE INDEX idx_notification_logs_jornada ON public.notification_logs USING btree (jornada_id);
CREATE INDEX idx_notification_logs_status ON public.notification_logs USING btree (status);
CREATE UNIQUE INDEX notification_logs_idempotency_key_key ON public.notification_logs USING btree (idempotency_key);
CREATE UNIQUE INDEX notification_preferences_worker_id_event_type_channel_key ON public.notification_preferences USING btree (worker_id, event_type, channel);
CREATE INDEX idx_open_bottle_events_bottle ON public.open_bottle_events USING btree (open_bottle_id, created_at DESC);
CREATE INDEX idx_open_bottles_location_product ON public.open_bottles USING btree (location_id, product_id) WHERE (status = 'OPEN'::text);
CREATE INDEX idx_open_bottles_venue_status ON public.open_bottles USING btree (venue_id, status);
CREATE INDEX idx_operational_expenses_venue_date ON public.operational_expenses USING btree (venue_id, expense_date);
CREATE INDEX idx_pickup_redemptions_bartender_created_at ON public.pickup_redemptions_log USING btree (bartender_id, created_at DESC);
CREATE INDEX idx_pickup_redemptions_log_bartender_id ON public.pickup_redemptions_log USING btree (bartender_id);
CREATE INDEX idx_pickup_redemptions_log_pos_time ON public.pickup_redemptions_log USING btree (pos_id, redeemed_at DESC);
CREATE INDEX idx_pickup_redemptions_log_redeemed_at ON public.pickup_redemptions_log USING btree (redeemed_at DESC);
CREATE INDEX idx_pickup_redemptions_log_result ON public.pickup_redemptions_log USING btree (result);
CREATE INDEX idx_pickup_redemptions_log_sale_id ON public.pickup_redemptions_log USING btree (sale_id);
CREATE INDEX idx_pickup_redemptions_log_token_bartender_time ON public.pickup_redemptions_log USING btree (pickup_token_id, bartender_id, redeemed_at DESC);
CREATE INDEX idx_pickup_redemptions_result_created_at ON public.pickup_redemptions_log USING btree (result, created_at DESC);
CREATE INDEX idx_pickup_redemptions_sale_id ON public.pickup_redemptions_log USING btree (sale_id);
CREATE INDEX idx_pickup_redemptions_venue ON public.pickup_redemptions_log USING btree (venue_id);
CREATE INDEX idx_pickup_redemptions_venue_created ON public.pickup_redemptions_log USING btree (venue_id, created_at);
CREATE INDEX idx_pickup_tokens_bar_location ON public.pickup_tokens USING btree (bar_location_id);
CREATE INDEX idx_pickup_tokens_jornada_id ON public.pickup_tokens USING btree (jornada_id);
CREATE INDEX idx_pickup_tokens_jornada_status ON public.pickup_tokens USING btree (jornada_id, status);
CREATE INDEX idx_pickup_tokens_sale ON public.pickup_tokens USING btree (sale_id);
CREATE INDEX idx_pickup_tokens_status ON public.pickup_tokens USING btree (status, issued_at);
CREATE INDEX idx_pickup_tokens_token ON public.pickup_tokens USING btree (token);
CREATE INDEX idx_pickup_tokens_venue_id ON public.pickup_tokens USING btree (venue_id);
CREATE UNIQUE INDEX pickup_tokens_token_key ON public.pickup_tokens USING btree (token);
CREATE INDEX idx_pos_terminals_is_cash_register ON public.pos_terminals USING btree (is_cash_register) WHERE (is_cash_register = true);
CREATE INDEX idx_pos_terminals_pos_type ON public.pos_terminals USING btree (pos_type);
CREATE INDEX idx_pos_terminals_venue_business ON public.pos_terminals USING btree (venue_id, business_type);
CREATE INDEX idx_pos_terminals_venue_zone ON public.pos_terminals USING btree (venue_id, zone);
CREATE UNIQUE INDEX pos_terminals_venue_code_unique ON public.pos_terminals USING btree (venue_id, code) WHERE (code IS NOT NULL);
CREATE INDEX idx_product_addons_venue ON public.product_addons USING btree (venue_id);
CREATE UNIQUE INDEX product_name_mappings_raw_name_venue_id_key ON public.product_name_mappings USING btree (raw_name, venue_id);
CREATE INDEX idx_products_active_in_sales ON public.products USING btree (is_active_in_sales) WHERE (is_active_in_sales = true);
CREATE INDEX idx_products_is_mixer ON public.products USING btree (is_mixer) WHERE (is_mixer = true);
CREATE INDEX idx_products_subcategory ON public.products USING btree (subcategory) WHERE (subcategory IS NOT NULL);
CREATE UNIQUE INDEX products_code_key ON public.products USING btree (code);
CREATE UNIQUE INDEX profiles_venue_rut_unique ON public.profiles USING btree (venue_id, rut_code) WHERE ((rut_code IS NOT NULL) AND (venue_id IS NOT NULL));
CREATE INDEX idx_provider_mappings_confidence ON public.provider_product_mappings USING btree (confidence_score DESC);
CREATE INDEX idx_provider_mappings_lookup ON public.provider_product_mappings USING btree (venue_id, provider_name, raw_product_name);
CREATE UNIQUE INDEX provider_product_mappings_venue_id_provider_name_raw_produc_key ON public.provider_product_mappings USING btree (venue_id, provider_name, raw_product_name);
CREATE INDEX idx_purchase_documents_status ON public.purchase_documents USING btree (status);
CREATE INDEX idx_purchase_documents_status_created_at ON public.purchase_documents USING btree (status, created_at DESC);
CREATE INDEX idx_purchase_documents_venue_created_at ON public.purchase_documents USING btree (venue_id, created_at DESC);
CREATE INDEX idx_purchase_import_audit_created ON public.purchase_import_audit USING btree (created_at DESC);
CREATE INDEX idx_purchase_import_audit_document ON public.purchase_import_audit USING btree (purchase_document_id);
CREATE INDEX idx_purchase_import_drafts_user_venue ON public.purchase_import_drafts USING btree (user_id, venue_id, status);
CREATE INDEX idx_purchase_import_lines_import ON public.purchase_import_lines USING btree (purchase_import_id);
CREATE INDEX idx_purchase_imports_venue_status ON public.purchase_imports USING btree (venue_id, status);
CREATE INDEX idx_purchase_items_classification ON public.purchase_items USING btree (classification);
CREATE INDEX idx_purchase_items_status ON public.purchase_items USING btree (item_status);
CREATE INDEX idx_purchases_venue ON public.purchases USING btree (venue_id);
CREATE UNIQUE INDEX purchases_purchase_import_id_key ON public.purchases USING btree (purchase_import_id);
CREATE INDEX idx_replenishment_plan_items_location ON public.replenishment_plan_items USING btree (to_location_id);
CREATE INDEX idx_replenishment_plan_items_plan ON public.replenishment_plan_items USING btree (replenishment_plan_id);
CREATE INDEX idx_replenishment_plan_items_product ON public.replenishment_plan_items USING btree (product_id);
CREATE INDEX idx_replenishment_plan_items_venue ON public.replenishment_plan_items USING btree (venue_id);
CREATE INDEX idx_replenishment_plans_jornada ON public.replenishment_plans USING btree (jornada_id);
CREATE INDEX idx_replenishment_plans_status ON public.replenishment_plans USING btree (status);
CREATE INDEX idx_replenishment_plans_venue ON public.replenishment_plans USING btree (venue_id);
CREATE INDEX idx_sale_item_addons_item ON public.sale_item_addons USING btree (sale_item_id);
CREATE INDEX idx_sale_items_venue ON public.sale_items USING btree (venue_id);
CREATE INDEX idx_sales_bar_location ON public.sales USING btree (bar_location_id);
CREATE INDEX idx_sales_jornada ON public.sales USING btree (jornada_id);
CREATE INDEX idx_sales_jornada_created_at ON public.sales USING btree (jornada_id, created_at DESC);
CREATE INDEX idx_sales_receipt_source ON public.sales USING btree (receipt_source);
CREATE INDEX idx_sales_sale_category ON public.sales USING btree (sale_category);
CREATE INDEX idx_sales_seller_created_at ON public.sales USING btree (seller_id, created_at DESC);
CREATE INDEX idx_sales_venue_created_at ON public.sales USING btree (venue_id, created_at DESC);
CREATE INDEX idx_sales_documents_document_type ON public.sales_documents USING btree (document_type);
CREATE UNIQUE INDEX idx_sales_documents_idempotency ON public.sales_documents USING btree (idempotency_key) WHERE (idempotency_key IS NOT NULL);
CREATE INDEX idx_sales_documents_retry ON public.sales_documents USING btree (status, next_retry_at) WHERE ((status = 'failed'::document_status) AND (next_retry_at IS NOT NULL));
CREATE INDEX idx_sales_documents_sale_created_at ON public.sales_documents USING btree (sale_id, created_at DESC);
CREATE INDEX idx_sales_documents_sale_id ON public.sales_documents USING btree (sale_id);
CREATE INDEX idx_sales_documents_status ON public.sales_documents USING btree (status);
CREATE INDEX idx_sales_documents_status_created_at ON public.sales_documents USING btree (status, created_at DESC);
CREATE INDEX idx_sales_documents_venue ON public.sales_documents USING btree (venue_id);
CREATE UNIQUE INDEX sales_documents_sale_id_key ON public.sales_documents USING btree (sale_id);
CREATE UNIQUE INDEX sidebar_config_venue_id_role_menu_key_key ON public.sidebar_config USING btree (venue_id, role, menu_key);
CREATE UNIQUE INDEX specific_tax_categories_code_key ON public.specific_tax_categories USING btree (code);
CREATE INDEX idx_stock_alerts_jornada ON public.stock_alerts USING btree (jornada_id);
CREATE INDEX idx_stock_alerts_venue ON public.stock_alerts USING btree (venue_id);
CREATE INDEX idx_stock_balances_venue ON public.stock_balances USING btree (venue_id);
CREATE UNIQUE INDEX stock_balances_product_id_location_id_key ON public.stock_balances USING btree (product_id, location_id);
CREATE UNIQUE INDEX stock_location_minimums_product_id_location_id_key ON public.stock_location_minimums USING btree (product_id, location_id);
CREATE INDEX idx_stock_lots_fefo ON public.stock_lots USING btree (product_id, location_id, expires_at, received_at) WHERE ((quantity > (0)::numeric) AND (is_depleted = false));
CREATE INDEX idx_stock_lots_venue_expires ON public.stock_lots USING btree (venue_id, expires_at);
CREATE INDEX idx_stock_lots_venue_product_location ON public.stock_lots USING btree (venue_id, product_id, location_id);
CREATE INDEX idx_stock_movements_cost_of_sales ON public.stock_movements USING btree (movement_type, source_type, jornada_id) WHERE ((movement_type = 'salida'::movement_type) AND (source_type = ANY (ARRAY['sale'::text, 'pickup'::text])));
CREATE INDEX idx_stock_movements_from_location_created_at ON public.stock_movements USING btree (from_location_id, created_at DESC);
CREATE INDEX idx_stock_movements_jornada ON public.stock_movements USING btree (jornada_id);
CREATE INDEX idx_stock_movements_jornada_created_at ON public.stock_movements USING btree (jornada_id, created_at DESC);
CREATE INDEX idx_stock_movements_lot ON public.stock_movements USING btree (stock_lot_id);
CREATE INDEX idx_stock_movements_pickup_token_id ON public.stock_movements USING btree (pickup_token_id);
CREATE INDEX idx_stock_movements_product_created_at ON public.stock_movements USING btree (product_id, created_at DESC);
CREATE INDEX idx_stock_movements_to_location_created_at ON public.stock_movements USING btree (to_location_id, created_at DESC);
CREATE INDEX idx_stock_movements_venue ON public.stock_movements USING btree (venue_id);
CREATE INDEX idx_stock_movements_venue_created ON public.stock_movements USING btree (venue_id, created_at);
CREATE INDEX idx_stock_predictions_venue ON public.stock_predictions USING btree (venue_id);
CREATE INDEX idx_stock_transfer_items_venue ON public.stock_transfer_items USING btree (venue_id);
CREATE INDEX idx_stock_transfers_venue ON public.stock_transfers USING btree (venue_id);
CREATE INDEX idx_supplier_aliases_product ON public.supplier_product_aliases USING btree (product_id);
CREATE INDEX idx_supplier_aliases_venue_lookup ON public.supplier_product_aliases USING btree (venue_id, supplier_name, normalized_text);
CREATE UNIQUE INDEX supplier_product_aliases_venue_id_supplier_name_normalized__key ON public.supplier_product_aliases USING btree (venue_id, supplier_name, normalized_text);
CREATE INDEX idx_ticket_sale_items_sale ON public.ticket_sale_items USING btree (ticket_sale_id);
CREATE INDEX idx_ticket_sale_items_venue ON public.ticket_sale_items USING btree (venue_id);
CREATE INDEX idx_ticket_sales_jornada ON public.ticket_sales USING btree (jornada_id);
CREATE INDEX idx_ticket_sales_jornada_created_at ON public.ticket_sales USING btree (jornada_id, created_at DESC);
CREATE INDEX idx_ticket_sales_jornada_pos ON public.ticket_sales USING btree (jornada_id, pos_id);
CREATE INDEX idx_ticket_sales_pos_id ON public.ticket_sales USING btree (pos_id);
CREATE INDEX idx_ticket_sales_venue ON public.ticket_sales USING btree (venue_id);
CREATE INDEX idx_ticket_sales_venue_created_at ON public.ticket_sales USING btree (venue_id, created_at DESC);
CREATE INDEX idx_ticket_sales_worker ON public.ticket_sales USING btree (sold_by_worker_id);
CREATE INDEX idx_ticket_sales_worker_created_at ON public.ticket_sales USING btree (sold_by_worker_id, created_at DESC);
CREATE UNIQUE INDEX ticket_sales_ticket_number_key ON public.ticket_sales USING btree (ticket_number);
CREATE INDEX idx_ticket_types_active ON public.ticket_types USING btree (venue_id, is_active);
CREATE INDEX idx_ticket_types_venue ON public.ticket_types USING btree (venue_id);
CREATE UNIQUE INDEX user_roles_user_id_role_key ON public.user_roles USING btree (user_id, role);
CREATE UNIQUE INDEX user_venue_roles_unique ON public.user_venue_roles USING btree (user_id, venue_id, role);
CREATE INDEX user_venue_roles_user_id_idx ON public.user_venue_roles USING btree (user_id);
CREATE INDEX user_venue_roles_venue_id_idx ON public.user_venue_roles USING btree (venue_id);
CREATE UNIQUE INDEX venues_slug_key ON public.venues USING btree (slug);
CREATE INDEX idx_waste_requests_created ON public.waste_requests USING btree (created_at DESC);
CREATE INDEX idx_waste_requests_location ON public.waste_requests USING btree (location_id);
CREATE INDEX idx_waste_requests_venue_product ON public.waste_requests USING btree (venue_id, product_id);
CREATE INDEX idx_waste_requests_venue_status ON public.waste_requests USING btree (venue_id, status);
CREATE UNIQUE INDEX worker_roles_unique ON public.worker_roles USING btree (worker_id, role);
