// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.2";

// src/lib/mcp/tools/get-active-jornada.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@3.0.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.83.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-active-jornada.ts
var get_active_jornada_default = defineTool({
  name: "get_active_jornada",
  title: "Jornada activa",
  description: "Devuelve la jornada (turno) actualmente abierta, si existe.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("jornadas").select("id, numero_jornada, nombre, fecha, hora_apertura, estado").eq("estado", "activa").order("created_at", { ascending: false }).limit(1);
    if (error) throw new ToolError(error.message);
    const j = data?.[0];
    if (!j) return { content: [{ type: "text", text: "No hay jornada activa." }] };
    const jornada = {
      id: String(j.id),
      numero: Number(j.numero_jornada),
      nombre: String(j.nombre ?? ""),
      fecha: String(j.fecha),
      hora_apertura: j.hora_apertura ? String(j.hora_apertura) : null
    };
    return { content: [{ type: "text", text: JSON.stringify(jornada) }], structuredContent: { jornada } };
  }
});

// src/lib/mcp/tools/list-jornadas.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z } from "npm:zod@^4.6.5";
var list_jornadas_default = defineTool2({
  name: "list_jornadas",
  title: "Listar jornadas",
  description: "Lista las jornadas m\xE1s recientes con su estado y fecha.",
  inputSchema: { limit: z.number().int().min(1).max(50).default(10).describe("Cantidad de jornadas (1-50).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("jornadas").select("id, numero_jornada, nombre, fecha, estado, forced_close").order("fecha", { ascending: false }).limit(limit);
    if (error) throw new ToolError2(error.message);
    const jornadas = (data ?? []).map((j) => ({
      id: String(j.id),
      numero: Number(j.numero_jornada),
      nombre: String(j.nombre ?? ""),
      fecha: String(j.fecha),
      estado: String(j.estado),
      cierre_forzado: Boolean(j.forced_close)
    }));
    return { content: [{ type: "text", text: JSON.stringify(jornadas) }], structuredContent: { jornadas } };
  }
});

// src/lib/mcp/tools/jornada-sales-summary.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z as z2 } from "npm:zod@^4.6.5";
var jornada_sales_summary_default = defineTool3({
  name: "get_jornada_sales_summary",
  title: "Resumen de ventas de jornada",
  description: "Total de ventas (CLP) de una jornada, desglosado por categor\xEDa, m\xE9todo de pago y punto de venta.",
  inputSchema: { jornada_id: z2.string().uuid().describe("ID de la jornada (usa list_jornadas o get_active_jornada).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ jornada_id }, ctx) => {
    const sb = supabaseForUser(ctx);
    const rows = [];
    for (let from = 0; ; from += 1e3) {
      const { data, error } = await sb.from("sales").select("total_amount, sale_category, payment_method, point_of_sale").eq("jornada_id", jornada_id).eq("is_cancelled", false).range(from, from + 999);
      if (error) throw new ToolError3(error.message);
      rows.push(...data ?? []);
      if (!data || data.length < 1e3) break;
    }
    const group = (key) => {
      const m = {};
      for (const r of rows) m[String(r[key])] = (m[String(r[key])] ?? 0) + Number(r.total_amount || 0);
      return Object.entries(m).map(([k, v]) => ({ clave: k, total: Math.round(v) }));
    };
    const summary = {
      jornada_id,
      ventas: rows.length,
      total_clp: Math.round(rows.reduce((s, r) => s + Number(r.total_amount || 0), 0)),
      por_categoria: group("sale_category"),
      por_metodo_pago: group("payment_method"),
      por_punto_venta: group("point_of_sale")
    };
    return { content: [{ type: "text", text: JSON.stringify(summary) }], structuredContent: { summary } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rboiblptylnsgcciutrk";
var mcp_default = defineMcp({
  name: "stockia",
  title: "STOCKIA",
  version: "0.1.0",
  instructions: "Herramientas de solo lectura de STOCKIA (Berl\xEDn Valdivia). Usa get_active_jornada o list_jornadas para obtener un jornada_id y luego get_jornada_sales_summary para ver ventas en CLP.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_active_jornada_default, list_jornadas_default, jornada_sales_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
